name: SSH Server with Reverse Tunnel

on:
  workflow_dispatch: # Allows manual workflow triggers

jobs:
  ssh-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH server
        run: |
          # Install OpenSSH server
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo service ssh start

          # Set up a password for the 'runner' user
          echo "runner:github" | sudo chpasswd

          # Create a reverse SSH tunnel to your Windows PC
          ssh -o StrictHostKeyChecking=no -R 2222:localhost:22 bilal@smexy.zapto.org -p 22

          # Keep the session alive
          while true; do sleep 60; done
