name: SSH Server

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push: # Optional: Trigger on code pushes

jobs:
  ssh-server:
    runs-on: ubuntu-latest # GitHub Actions uses Linux runners for SSH
    steps:
      - name: Set up SSH server
        run: |
          # Install and start OpenSSH server
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo service ssh start

          # Set up a password for the 'runner' user
          echo "runner:github" | sudo chpasswd

          # Retrieve and print public IP address
          public_ip=$(curl -s http://ifconfig.me)
          echo "SSH server is ready. Use the following command to connect:"
          echo "ssh runner@${public_ip}"

          # Keep the workflow alive with an infinite loop
          echo "Keeping the SSH server alive..."
          while true; do sleep 60; done
